version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
<<<<<<< HEAD
=======
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
>>>>>>> 28551017a6599ea34a4cf9bcf44e4e512977c52a

jobs:
  build:
    working_directory: ~/example_application
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
<<<<<<< HEAD
          name: install-npm
          command: npm install
      - run:
	  name: test-run
          command: npm run test
=======
          name: install-npm-wee
          command: npm install
>>>>>>> 28551017a6599ea34a4cf9bcf44e4e512977c52a
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
<<<<<<< HEAD
=======
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf ExampleApplication/; git clone https://github.com/Wenhao-F/ExampleApplication.git; source ExampleApplication/deploy.sh"
>>>>>>> 28551017a6599ea34a4cf9bcf44e4e512977c52a
